print(package.path)
print(package.cpath)
print("hello")
print("This is my world!")
print(sysargv.net)
sysargv.net=1
print(sysargv.net)
print(appdata)
sysargv.save("confignew.ini")
log.i("This is my world!")
log.n("This is my world!")
log.t("This is my world!")
print(instancesmanager)
local m = require("testapi")
m.d("This is my world!")